name: Home Heat Map
version: "0.1.1"
slug: home_heat_map
url: https://github.com/MrPsyware/HA-HomeHeatMap
description: Floor plan heatmaps for temperature, humidity and wireless signals
arch:
  - amd64
  - aarch64
startup: application
boot: auto
init: false
homeassistant_api: true
ingress: true
ingress_port: 8099
panel_icon: mdi:home-thermometer-outline
panel_title: Heat Map
options: {}
schema: {}
